// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZRXEtjY-5WqPnAUsXZLSFoa6WMMwHBs',
    appId: '1:1003220743691:web:43ec9ced5c50eb657ab90e',
    messagingSenderId: '1003220743691',
    projectId: 'flutter-homura-2',
    authDomain: 'flutter-homura-2.firebaseapp.com',
    storageBucket: 'flutter-homura-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60Z9MEyxSJ6pnSjbAR5w2osS3iTUMTWo',
    appId: '1:1003220743691:android:b91312a00db14d587ab90e',
    messagingSenderId: '1003220743691',
    projectId: 'flutter-homura-2',
    storageBucket: 'flutter-homura-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAssiNvTKTIOzwJErreBDhOVq8VUlLriTM',
    appId: '1:1003220743691:ios:7d70951f5f7382a37ab90e',
    messagingSenderId: '1003220743691',
    projectId: 'flutter-homura-2',
    storageBucket: 'flutter-homura-2.appspot.com',
    iosClientId: '1003220743691-u09ttukcn2obksn680bt51upopmkbh4t.apps.googleusercontent.com',
    iosBundleId: 'com.flutter-homura-2.app',
  );
}
